[build]
command = "(corepack enable || true) && pnpm install --frozen-lockfile && npx turbo run build --filter=@closebuy/rider"
publish = "apps/rider/.next"

[[plugins]]
package = "@netlify/plugin-nextjs"
