[build]
command = "(corepack enable || true) && pnpm install --frozen-lockfile && npx turbo run build --filter=@closebuy/admin"
publish = "apps/admin/.next"

[[plugins]]
package = "@netlify/plugin-nextjs"
