[build]
command = "(corepack enable || true) && pnpm install --frozen-lockfile && npx turbo run build --filter=@closebuy/customer"
publish = "apps/customer/.next"

[[plugins]]
package = "@netlify/plugin-nextjs"
